### ISSUE TITLE
FYI - being reported as a 'deceptive site'

### ISSUE THREAD

**Issue by mendhak** [abevoelker/how-long-since-google-said-a-google-drive-linux-client-is-coming#2]
Chrome/Firefox desktop are showing this countdown site as deceptive. 

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fabevoelker.github.io%2Fhow-long-since-google-said-a-google-drive-linux-client-is-coming%2F&hl=en-US

> "Try to trick visitors into sharing personal info or downloading software"

Though I can't see why this would be the case. The code has remained unchanged.   Would activity on other github pages under abevoelker.github.io cause this to happen?

You can report it as an incorrect forgery alert:

https://safebrowsing.google.com/safebrowsing/report_error/?tpl=mozilla&hl=en-US&url=https%3A%2F%2Fabevoelker.github.io%2Fhow-long-since-google-said-a-google-drive-linux-client-is-coming%2F

Screenshot:
![image](https://user-images.githubusercontent.com/746276/43122098-bf9a07fe-8f17-11e8-9e66-5f5f20a5e3ec.png)

**Comment by abevoelker** [comment]
Wow thanks for the heads-up, that is pretty weird! As you said I certainly haven't changed the page recently or done anything shady with it. I guess Google is getting a little salty :stuck_out_tongue: 

I'm pretty sure this is the only repo I have GitHub Pages enabled on so it would have to be this specific page, not some other abevoelker.github.io page triggering it: https://duckduckgo.com/?q=site%3Aabevoelker.github.io&t=h_&ia=web

I've reported it as an incorrect alert using your link; not sure what else I can do about it.

Thanks again!

**Comment by mendhak** [comment]
Hey looks like our two reports may have fixed it 🎉 

Not marked as deceptive anymore.  They have seen the truth.

Let's mark this as resolved.

**Comment by abevoelker** [comment]
Woohoo! :tada: 

Lesson learned: if I criticize Google again, continue doing it from Github Pages sites so my personal blog doesn't get blackholed :laughing:
